loadstring(game:HttpGetAsync("https://pastebin.com/raw/Z5ykhhdt"))()
loadstring(game:HttpGetAsync("https://pastebin.com/raw/v7Aai7m8"))()
warn("Hydroxide has been loaded!")
warn("You are the updated Hydroxide version is " .. HydroxideVersion .. " and you are currently on " .. version .. "!")
warn(MSG)
